version = 0.1
[default.deploy.parameters]
stack_name = "aws-serverless-websockets"
resolve_s3 = true
s3_prefix = "aws-serverless-websockets"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
